### PR TITLE
Equpment Documentation start

### PR DESCRIPTION
**Pull request by ItinerantEngineer**
Created folder structure for Equipment Documentation, added some for the Laser Cutter

### CODE REVIEW

**Comment by jamcole** [comment]
great work!

**Comment by Ths2-9Y-LqJt6** [comment]
OMG!  Yes, great work indeed. You get a super duper gold star for being the first outside coder to issue a pull request - thanks!

If you're up for another round of writing, I suggest  we tidy a few things up! Specifically:
* removing one of the "cardinal rule of RetinaEngrave" uses. There's one on the [double sided page](https://rtfm.synshop.org/users/Equipment%20Documentation/Laser%20Cutter/DoubleSidedEngraving/) and one on [the basics page](https://rtfm.synshop.org/users/Equipment%20Documentation/Laser%20Cutter/LaserCutterBasics/). 
* you have the same content on both the [index](https://github.com/synshop/rtfm/blob/master/docs/users/Equipment%20Documentation/Laser%20Cutter/index.md) and [basics page](https://github.com/synshop/rtfm/blob/master/docs/users/Equipment%20Documentation/Laser%20Cutter/LaserCutterBasics.md).  Let's just remove [the basics](https://github.com/synshop/rtfm/blob/master/docs/users/Equipment%20Documentation/Laser%20Cutter/LaserCutterBasics.md) and leave the [index](https://github.com/synshop/rtfm/blob/master/docs/users/Equipment%20Documentation/Laser%20Cutter/index.md).
* This sentence is not a good to have in guide for first time readers, "The cardinal rule of RetinaEngrave is that it's stupid.". Something like this would be a lot more welcoming, "RetinaEngrave has many frustrating aspects, but you can make it work to do you laser cutter bidding". I'm open to ideas here, but moving away from "it's stupid" ;)
* Let's add links to the FSL [download page](https://fslaser.com/RetinaEngrave) on the [index page](https://rtfm.synshop.org/users/Equipment%20Documentation/Laser%20Cutter/)

thanks again!

**Comment by ItinerantEngineer** [comment]
We can definitely clean it up, those are straight copies of things from my synshop.org blog that I knew would be useful to test out how Github and Mkdocs works and more notes for myself for later and casual things than real documentation :)

Before I did any more content, I did want to ask if there is any particular reason we want to keep the menu auto generated instead of being defined by a nav section in the  .yml?  Would think we'd really prefer Equipment Documentation -> Piece of Equipment take you to the index page instead of having to specify a Home/index page, and that page that then has bunches of links to subpages, manufacturer's manuals, etc etc but it seems with the auto generation that that is both not possible.

Also it seems to not always work, or maybe its just me? Like if I go to rtfm.synshop.org for the first time, under Users, Equipment Documentation, Laser Cutter, I see 'DoubleSidedEngraving', 'LaserCutterBasics', and 'Home' which are names of files, except for Home(maybe that's index?) and missing the AI.md file entirely, but if I click on any of those pages, and open the Menu again, now I see 'Double Sided Laser Engraving', 'Laser Cutter', and 'Home', which are the header values in those files(aside from Home).

**Comment by Ths2-9Y-LqJt6** [comment]
@ItinerantEngineer  - I'd tried to avoid using the ``nav:`` option in ``mkdocs.yml`` file as I wanted to avoid the extra maintenance.  That said, there's definitely something funky going on with the nav! @jamcole is there any way we can check the version of ``mkdocs`` travis is running? I forced and upgrade locally and I see more items in the nav than on the live site.

We'll figure this!

**Comment by Ths2-9Y-LqJt6** [comment]
@jamcole  - Interesting! I was having problems and checked my version. Here it is before upgrading, installed via ``apt``:
```
$ mkdocs --version                                                                                                                                      
mkdocs, version 0.16.3   
```
After upgrading, installed via ``pip``:
```
$  mkdocs --version                                                                                                        
mkdocs, version 1.0.1 from /home/mrjones/.local/lib/python2.7/site-packages/mkdocs (Python 2.7)  
```
And I see that travis is running ``mkdocs-0.17.5``. I see our [``travis.yml``](https://github.com/synshop/rtfm/blob/master/.travis.yml) just specifies ``- sudo pip install mkdocs``.  Seems like we'll have to research the massive difference of the 0.x travis and I have before vs 1.x version I have now.

/me does a search

Ah, interesting. 1.0 came out [Aug 3, 2018](https://www.mkdocs.org/about/release-notes/#version-10-2018-08-03). Maybe travis will just catch up?

**Comment by jamcole** [comment]
I'm not sure what the base builder image is, we're just using the "python" one - I'd expect pip to grab the latest though... Unless they're running a package proxy (which only makes sense if they're doing tons of builds) - Though over two weeks to get latest seems a little long.

**Comment by Ths2-9Y-LqJt6** [comment]
WHEW!! Took a while, but I finally [got it all sorted](https://github.com/synshop/rtfm/pull/9): I had some [janky CSS](https://github.com/synshop/rtfm/pull/9/files#diff-1d2e16ad126f71b1ba267a507423c72b) that was hiding key ``<li>`` items.  Once I fixed that, all the navigation fell into place and is working now as expected.

@ItinerantEngineer  - I updated your docs in two ways.  I made them a single page and I removed the "is stupid" part.  Feel free to update if you think I did wrong - I take no offense!  

@jamcole & @ItinerantEngineer  - Thanks both of you for you patience while I figured this out.  We're not firing on all cylinders and are ready for more content with non-broke navigation - w00t!

**Pull request merged**
