### PR TITLE
Consew 230 Industrial Sewing Machine Documentation

### PR DESCRIPTION
**Pull request by ItinerantEngineer**
Excuse the excessive commit count, was testing SlackEdit.io and its syncing was a bit ridiculous.

### CODE REVIEW

**Comment by Ths2-9Y-LqJt6** [comment]
Heh - no worries about the excessive commits ;)

The content is great and a welcome addition - thank you!

The only change is that the images appear to be the raw size from your phone, thus are too big for the web page.  Each one is multiple megs, when they should be no larger than about 300k.  The easiest way to reduce their size is to make them smaller. I'd say about 1000px on the largest size? You could try smaller if you wanted.  The goal would be to get it as small as possible in disk/download size but not loose the any details - specifically where the the thread interfaces with each part of the machine.

Thanks again and let me know if you need a hand on the resizing!

**Comment by ItinerantEngineer** [comment]
Hmm, when I served the pages locally on MkDocs they seemed to resize into
the page, and I left them big in case it's auto resizing needed a minimum
resolution. Busy at the shop today, but I can look up what minimum
resolution it needs later, or if your know offhand feel free to resize!

**Comment by ItinerantEngineer** [comment]
Updated!

**Comment by Ths2-9Y-LqJt6** [comment]
Awesome - thanks a bunch - Merging!

**Pull request merged**
